/*
 * Project configuration...
 */
ThisBuild / scalaVersion := "3.8.1"
ThisBuild / version := "0.0.14"
/*
 * Static analysis configuration...
 */
ThisBuild / scalacOptions ++= Seq("-Werror", "-Wall", "-Wunused:all")
/*
 * Scaladoc configuration...
 */
Compile / doc / target := baseDirectory.value / "target" / "api" / "scaladoc"
Compile / doc / scalacOptions ++= Seq(
  "-project",
  name.value,
  "-project-version",
  version.value
)
/*
 * Wartremover configuration...
 */
ThisBuild / wartremoverErrors ++= {
  val excluded = Set(Wart.Var, Wart.Any)
  Warts.unsafe.filterNot(excluded.contains)
}
/*
 * Scoverage configuration...
 * Excludes:
 *  - entrypoint
 *  - excludes other synthetic classes generated by scala compiler
 */
val coverageThreshold = 70
ThisBuild / coverageFailOnMinimum := true
ThisBuild / coverageMinimumStmtTotal := coverageThreshold
ThisBuild / coverageMinimumBranchTotal := coverageThreshold
ThisBuild / coverageExcludedFiles := ".*Main.*"
ThisBuild / coverageHighlighting := true
/*
 * Common libraries between subprojects...
 */
ThisBuild / libraryDependencies ++= Dependencies.testing

lazy val generateReport = taskKey[Unit]("Generate project report.")

/*
 * Project definition...
 */
lazy val root = (project in file("."))
  .settings(
    name := "scala3-template",
    // Assembly configuration...
    assembly / assemblyJarName := s"${name.value}-${version.value}-fat.jar",
    assembly / assemblyOutputPath := baseDirectory.value / "target" / "dist" / s"${name.value}-${version.value}-fat.jar",
    assembly / assemblyMergeStrategy := {
      case PathList("META-INF", _*) => MergeStrategy.discard
      case _                        => MergeStrategy.first
    },
    generateReport := {
      import scala.sys.process._
      import sbt.IO
      val log = streams.value.log
      val inputFile = "docs/report.qd"
      val outputDir = baseDirectory.value / "target" / "dist"
      IO.createDirectory(outputDir)
      s"quarkdown c $inputFile --pdf -o ${outputDir.getAbsolutePath} --out-name report".!
    }
  )
/*
 * Run static and dynamic analysis...
 */
addCommandAlias("check", "; fmtCheck; coverage; test")
/*
 * Run the entirely build lifecycle...
 */
addCommandAlias("build", "; fmtCheck; assembly; doc; generateReport")
/*
 * Format...
 */
addCommandAlias("fmt", "; scalafmtAll; scalafmtSbt")
/*
 * Check format...
 */
addCommandAlias("fmtCheck", "; scalafmtCheckAll; scalafmtSbtCheck")
