import scala.sys.process.{Process, ProcessLogger}

/*
 * Project configuration...
 */
ThisBuild / scalaVersion := "3.8.1"
ThisBuild / version := "0.0.16"
/*
 * Static analysis configuration...
 */
ThisBuild / scalacOptions ++= Seq("-Werror", "-Wall", "-Wunused:all")
/*
 * Scaladoc configuration...
 */
Compile / doc / target := baseDirectory.value / "target" / "api" / "scaladoc"
Compile / doc / scalacOptions ++= Seq(
  "-project",
  name.value,
  "-project-version",
  version.value
)
/*
 * Wartremover configuration...
 */
ThisBuild / wartremoverErrors ++= {
  val excluded = Set(Wart.Var, Wart.Any)
  Warts.unsafe.filterNot(excluded.contains)
}
/*
 * Scoverage configuration...
 * Excludes:
 *  - entrypoint
 *  - excludes other synthetic classes generated by scala compiler
 */
val coverageThreshold = 70
ThisBuild / coverageFailOnMinimum := true
ThisBuild / coverageMinimumStmtTotal := coverageThreshold
ThisBuild / coverageMinimumBranchTotal := coverageThreshold
ThisBuild / coverageExcludedFiles := ".*Main.*"
ThisBuild / coverageHighlighting := true
/*
 * Common libraries between subprojects...
 */
ThisBuild / libraryDependencies ++= Dependencies.testing

/*
 * Report task keys
 */
lazy val generateReportHtml = taskKey[Unit]("Generate the HTML project report.")
lazy val generateReportPdf = taskKey[Unit]("Generate the PDF project report.")
lazy val generateReport =
  taskKey[Unit]("Generate the project report artifacts.")

/*
 * Project definition...
 */
lazy val root = (project in file("."))
  .settings(
    name := "scala3-template",
    // Assembly configuration...
    assembly / assemblyJarName := s"${name.value}-${version.value}-fat.jar",
    assembly / assemblyOutputPath := baseDirectory.value / "target" / "dist" / s"${name.value}-${version.value}-fat.jar",
    assembly / assemblyMergeStrategy := {
      case PathList("META-INF", _*) => MergeStrategy.discard
      case _                        => MergeStrategy.first
    },
    // Report Generation Tasks
    generateReportHtml := {
      val log = streams.value.log
      val inputFile = baseDirectory.value / "docs" / "report.qd"
      val outputDir = target.value / "api" / "report"
      IO.createDirectory(outputDir)
      val command = Seq(
        "quarkdown",
        "c",
        inputFile.getAbsolutePath,
        "-o",
        outputDir.getAbsolutePath,
        "--out-name",
        "report"
      )
      val exitCode =
        Process(command).!(ProcessLogger(log.info(_), log.error(_)))
      if (exitCode != 0)
        sys.error("Quarkdown failed while generating HTML report")
    },
    generateReportPdf := {
      val log = streams.value.log
      val inputFile = baseDirectory.value / "docs" / "report.qd"
      val outputDir = target.value / "dist"
      IO.createDirectory(outputDir)
      val command = Seq(
        "quarkdown",
        "c",
        inputFile.getAbsolutePath,
        "-o",
        outputDir.getAbsolutePath,
        "--out-name",
        "report",
        "--pdf"
      )
      val exitCode =
        Process(command).!(ProcessLogger(log.info(_), log.error(_)))
      if (exitCode != 0)
        sys.error("Quarkdown failed while generating PDF report")
    },
    generateReport := {
      generateReportHtml.value
      generateReportPdf.value
    }
  )
/*
 * Run static and dynamic analysis...
 */
addCommandAlias("check", "; fmtCheck; coverage; test")
/*
 * Run the entirely build lifecycle...
 */
addCommandAlias("build", "; fmtCheck; assembly; doc; generateReport")
/*
 * Format...
 */
addCommandAlias("fmt", "; scalafmtAll; scalafmtSbt")
/*
 * Check format...
 */
addCommandAlias("fmtCheck", "; scalafmtCheckAll; scalafmtSbtCheck")
