name: Publish Scaladoc

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Generate Scaladoc
        run: sbt "set Compile / doc / target := file("./target/api"); doc"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/api
          publish_branch: gh-pages
